services:
  - type: web
    name: ecommerce-django
    env: python
    rootDir: backend_django
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate --noinput && python manage.py create_initial_superuser && python manage.py collectstatic --noinput && gunicorn backend_django.wsgi:application
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "ecommerce-django.onrender.com"
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString

databases:
  - name: ecommerce-db
    plan: free
